version: '3'

services:
  bitwardenrs:
    image: codejamninja/bitwardenrs:latest
    ports:
      - 8080:80

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: data
