version: '3'

services:
  bitwardenrs:
    image: codejamninja/bitwardenrs:latest
    ports:
      - 8080:80

  postgres:
    image: postgres:12.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: ~
