#!/bin/sh

if [ -z "$POSTGRES_URL" ]; then
  export POSTGRES_URL="postgresql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE"
fi
export DATABASE_URL=$POSTGRES_URL

exec /bitwarden_rs $@
